# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ar-enums}
  s.version = "0.3.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Emmanuel Nicolau"]
  s.date = %q{2010-08-12}
  s.description = %q{Provides a simple way for defining enumerations in ActiveRecord models}
  s.email = %q{emmanicolau@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".autotest",
     ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "ar-enums.gemspec",
     "examples/internal_enums.rb",
     "lib/ar-enums.rb",
     "lib/enum.rb",
     "lib/enum_block.rb",
     "lib/enum_definition.rb",
     "lib/enum_field.rb",
     "lib/factory.rb",
     "lib/metaprogramming_extensions.rb",
     "lib/options_helper.rb",
     "spec/enum_definition_spec.rb",
     "spec/enum_spec.rb",
     "spec/factory_spec.rb",
     "spec/schema.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/eeng/ar-enums}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Enumerations for ActiveRecord models}
  s.test_files = [
    "spec/enum_definition_spec.rb",
     "spec/enum_spec.rb",
     "spec/factory_spec.rb",
     "spec/schema.rb",
     "spec/spec_helper.rb",
     "examples/internal_enums.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

