module ArEnums
  def self.included(base)
    base.send :extend, ClassMethods
  end
  
  module ClassMethods
    # == Inline enumerations from an array of values
    # 
    # This is the simplest case. The values are stored as ordinals in a foreign_key, similar to a belongs_to association. 
    # They are autogenerated starting at 1.
    # 
    #   class TrafficLight < ActiveRecord::Base
    #     enum :state, %w[red green yellow]
    #   end
    # 
    #   tl = TrafficLight.new(:state => :green)
    #   tl.state_id   # => 2    
    #   tl.state      # => #<ActiveRecord::Enum @label_method=:titleize, @name="green", @id=2>
    # 
    # == Inline enumerations from an array of hashes
    # 
    # This allows you to define new columns in the Enum value. If the :id is not specified is generated for you.
    # 
    #   class TrafficLight < ActiveRecord::Base
    #     enum :state, [
    #       { :name => :red, :stop_traffic => true, :rgb => 0xF00 },
    #       { :name => :green, :stop_traffic => false, :rgb => 0x0F0 }
    #     ]
    #   end
    # 
    #   tl = TrafficLight.new(:state => :green)
    #   tl.state_id       # => 2    
    #   tl.stop_traffic   # => false
    #   tl.rgb            # => 0x0F0
    # 
    def enum field_name, values, options = {}
      field = EnumField.new field_name
      enums = create_enums values, options
      define_enums_getter field, enums      
      define_enum_getter_and_setter field, enums      
    end
    
    private
    def create_enums values, options
      values.map { |value| ActiveRecord::Enum.create_from(value, values, options) }
    end
    
    def define_enums_getter field, enums
      define_class_method(field.enums_getter) { enums }
    end
    
    def define_enum_getter_and_setter field, enums
      define_method field.name do
        enums.detect { |enum| enum.id == read_attribute(field.foreign_key) }    
      end                                                                       
      
      define_method "#{field.name}=" do |value|
        write_attribute field.foreign_key, enums.detect { |enum| enum == value }.try(:id)
      end
    end
  end
end

ActiveRecord::Base.send :include, ArEnums